apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.service.httpPort }}
      targetPort: http
  selector:
    app: {{ .Release.Name }}-service