apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-activemq
spec:
  type: {{ .Values.activemq.service.type }}
  ports:
    - name: admin
      port: {{ .Values.activemq.service.adminPort }}
      targetPort: admin
    - name: tcp
      port: {{ .Values.activemq.service.tcpPort }}
      targetPort: tcp
  selector:
    app: {{ .Release.Name }}-activemq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-activemq
  labels:
    app: {{ .Release.Name }}-activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-activemq
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-activemq
    spec:
      containers:
        - name: {{ .Release.Name }}-activemq
          image: "{{ .Values.activemq.image.repository }}:{{ .Values.activemq.image.tag }}"
          imagePullPolicy: "Always"
          ports:
            - containerPort: {{ .Values.activemq.service.adminPort }}
              name: admin
            - containerPort: {{ .Values.activemq.service.tcpPort }}
              name: tcp