apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mockserver
spec:
   type: {{ .Values.mockserver.service.type }}
   ports:
     - name: port
       port: {{ .Values.mockserver.service.port }}
       targetPort: port
   selector:
        app: {{ .Release.Name }}-mockserver