apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mockserver
spec:
  type: {{ .Values.mockserver.service.type }}
  ports:
    - name: port
      port: {{ .Values.mockserver.service.port }}
      targetPort: port
  selector:
    app: {{ .Release.Name }}-mockserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mockserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mockserver
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mockserver
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      imagePullSecrets:
        - name: cloudsmith-pull-secret
      containers:
        - name: {{ .Release.Name }}-mockserver
          image: "{{ .Values.mockserver.image.repository }}:{{ .Values.mockserver.image.tag }}"
          ports:
            - containerPort: {{ .Values.mockserver.service.port }}
              name: port
          env:
            - name: CLOUDSMITH_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsmith-secret
                  key: username
            - name: CLOUDSMITH_PASS
              valueFrom:
                secretKeyRef:
                  name: cloudsmith-secret
                  key: password