apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql
spec:
  type: {{ .Values.postgres.service.type }}
  ports:
    - name: postgresql
      port: {{ .Values.postgres.service.pgPort }}
      targetPort: postgresql
  selector:
    app: {{ .Release.Name }}-postgresql