apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  type: {{ .Values.service.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.service.httpPort }}
      targetPort: http
  selector:
    app: {{ .Release.Name }}-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-service
    spec:
      imagePullSecrets:
        - name: cloudsmith-pull-secret
      containers:
        - name: {{ .Release.Name }}-service
          image: "{{ .Values.service.image.repository }}:{{ .Values.service.image.tag }}"
          ports:
            - name: http
              containerPort: {{ .Values.service.service.httpPort }}
          env:
            - name: CLOUDSMITH_USER
              valueFrom:
                secretKeyRef:
                  name: cloudsmith-secret
                  key: username
            - name: CLOUDSMITH_PASS
              valueFrom:
                secretKeyRef:
                  name: cloudsmith-secret
                  key: password
            - name: ConnectionStrings__SpreekuurUitnodigingenConnection
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ServiceConnectionString
            - name: ActiveMQ__Protocol
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ACTIVEMQ_PROTOCOL
            - name: ActiveMQ__Host
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ACTIVEMQ_HOST
            - name: ActiveMQ__Port
              value: "{{ .Values.activemq.service.tcpPort }}"
            - name: Mockserver__Url
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MockServerUrl