name: Deploy Helm Chart

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        container: [1, 2, 3]
        fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: 'latest'

      - name: Configure kubectl
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Deploy Helm Chart
        run: helm upgrade --install spreekuur-uitnodigingen-test helm-chart
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          record: true
          parallel: true
          group: 'End-to-End Tests'
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  
  cleanup:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Set up Kubernetes
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'
      - name: Configure kubectl
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Wait for Cypress job to complete
        id: wait_for_completion
        run: |
          echo "Waiting for Cypress job to complete..."
          kubectl wait --for=condition=complete --timeout=600s job/{{ steps.deploy.outputs.release_name }}-cypress

      - name: Uninstall Helm Chart
        if: ${{ steps.wait_for_completion.outcome == 'success' }}
        run: helm uninstall spreekuur-uitnodigingen-test
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
