name: Deploy Helm Chart and Run Cypress Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    
env:
  CLOUDSMITH_REGISTRY: docker.cloudsmith.io

jobs:
  checkout-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
  
  set-up-cluster:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube status

      - name: Set up kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl config use-context minikube

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  
  set-up-cloudsmith:
    runs-on: ubuntu-latest   
    
    steps:
      - name: Login to Cloudsmith
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CLOUDSMITH_REGISTRY }}
          username: ${{ secrets.CLOUDSMITH_USERNAME }}
          password: ${{ secrets.CLOUDSMITH_PASSWORD }}   
          
      - name: Create cloudsmith-secret
        run: |
          kubectl create secret generic cloudsmith-secret \
          --from-literal=username=${{ secrets.CLOUDSMITH_USERNAME }} \
          --from-literal=password=${{ secrets.CLOUDSMITH_PASSWORD }}

      - name: Create cloudsmith-pull-secret
        run: |
          kubectl create secret docker-registry cloudsmith-pull-secret \
          --docker-server=${{ env.CLOUDSMITH_REGISTRY }} \
          --docker-username=${{ secrets.CLOUDSMITH_USERNAME }} \
          --docker-password=${{ secrets.CLOUDSMITH_PASSWORD }}

  deploy-helm:
    runs-on: ubuntu-latest
    
    steps:          
      - name: Deploy Helm Chart
        run: |
          helm upgrade --install spreekuur-uitnodigingen-test ./charts/run-cypress
          sleep 60
          kubectl get all
          sleep 60
          kubectl get all

      - name: Wait for Cypress job to complete
        run: |
          sleep 10
          kubectl wait --for=condition=complete pod -l app=spreekuur-uitnodigingen-test-cypress --namespace default