name: Deploy Helm Chart and Run Cypress Tests

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube status

      - name: Set up kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
          kubectl config use-context minikube

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
          
      - name: Create cloudsmith-secret
        run: |
          kubectl create secret generic cloudsmith-secret \
          --from-literal=username=${{ secrets.CLOUDSMITH_USERNAME }} \
          --from-literal=password=${{ secrets.CLOUDSMITH_PASSWORD }}
          
      - name: Create cloudsmith-pull-secret
        run: |
          kubectl create secret generic cloudsmith-pull-secret \
          --from-literal=username=${{ secrets.CLOUDSMITH_USERNAME }} \
          --from-literal=password=${{ secrets.CLOUDSMITH_PASSWORD }}
          
      - name: Login to Cloudsmith
        uses: docker/login-action@v2
        with:
          registry: docker.cloudsmith.io/topicus-healthcare/viplive
          username: ${{ secrets.CLOUDSMITH_USERNAME }}
          password: ${{ secrets.CLOUDSMITH_PASSWORD }}

      - name: Deploy Helm Chart
        run: |
          helm upgrade --install spreekuur-uitnodigingen-test ./helm-chart
          sleep 60
          kubectl get all
          kubectl describe pod -l app=spreekuur-uitnodigingen-test-webservice --namespace default

      - name: Check for pod failures
        if: failure()
        run: |
          kubectl get pods --all-namespaces
          kubectl describe pods --all-namespaces | grep -A 10 -i "image pull"

      - name: Wait for Cypress job to complete
        run: |
          kubectl wait --for=condition=complete --timeout=600s pod -l app=spreekuur-uitnodigingen-test-cypress --namespace default

      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
          group: 'End-to-End Tests'